/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pgmsapp;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author urn
 */
public class AdminPortal extends javax.swing.JFrame {

    /**
     * Creates new form AdminPortal
     */
    public AdminPortal(ResultSet rs) {
        
            initComponents();
            try{
            tfUName.setText(rs.getString("u_name"));
        } catch (SQLException ex) {
            Logger.getLogger(AdminPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCard = new javax.swing.JPanel();
        cardGrievances1 = new pgmsapp.cardGrievances();
        panelAdminShow = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tfUName = new javax.swing.JTextField();
        btnViewGrievance = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnLogOut1 = new javax.swing.JButton();
        btnLogOut3 = new javax.swing.JButton();
        btnLogOut4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCard.setLayout(new java.awt.CardLayout());
        panelCard.add(cardGrievances1, "cardGrievanceView");

        getContentPane().add(panelCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 11, 577, 478));

        panelAdminShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Logged in as-");
        panelAdminShow.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 27));

        tfUName.setEditable(false);
        tfUName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelAdminShow.add(tfUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 30));

        btnViewGrievance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewGrievance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnViewGrievance.setText("View Grievances");
        btnViewGrievance.setToolTipText("");
        btnViewGrievance.setBorder(null);
        btnViewGrievance.setBorderPainted(false);
        btnViewGrievance.setContentAreaFilled(false);
        btnViewGrievance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewGrievance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewGrievance.setInheritsPopupMenu(true);
        btnViewGrievance.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnViewGrievance.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnViewGrievance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGrievanceActionPerformed(evt);
            }
        });
        panelAdminShow.add(btnViewGrievance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 60));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Please select an Option");
        panelAdminShow.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 27));

        btnLogOut1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogOut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnLogOut1.setText("Logout");
        btnLogOut1.setToolTipText("");
        btnLogOut1.setBorder(null);
        btnLogOut1.setBorderPainted(false);
        btnLogOut1.setContentAreaFilled(false);
        btnLogOut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut1.setInheritsPopupMenu(true);
        btnLogOut1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnLogOut1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnLogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut1ActionPerformed(evt);
            }
        });
        panelAdminShow.add(btnLogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 220, 60));

        btnLogOut3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogOut3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnLogOut3.setText("User Approval Requests");
        btnLogOut3.setToolTipText("");
        btnLogOut3.setBorder(null);
        btnLogOut3.setBorderPainted(false);
        btnLogOut3.setContentAreaFilled(false);
        btnLogOut3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut3.setInheritsPopupMenu(true);
        btnLogOut3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnLogOut3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnLogOut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut3ActionPerformed(evt);
            }
        });
        panelAdminShow.add(btnLogOut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 60));

        btnLogOut4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogOut4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnLogOut4.setText("Manage Users");
        btnLogOut4.setToolTipText("");
        btnLogOut4.setBorder(null);
        btnLogOut4.setBorderPainted(false);
        btnLogOut4.setContentAreaFilled(false);
        btnLogOut4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut4.setInheritsPopupMenu(true);
        btnLogOut4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnLogOut4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnLogOut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut4ActionPerformed(evt);
            }
        });
        panelAdminShow.add(btnLogOut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 60));

        getContentPane().add(panelAdminShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 478));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewGrievanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGrievanceActionPerformed
      panelCard.removeAll();
       panelCard.add(new cardGrievances());
       panelCard.repaint();
       panelCard.revalidate();
    }//GEN-LAST:event_btnViewGrievanceActionPerformed

    private void btnLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut1ActionPerformed
        try {
            // TODO add your handling code here:
            this.dispose();
            new PGMSLogin().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogOut1ActionPerformed

    private void btnLogOut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut3ActionPerformed
        // TODO add your handling code here:
        panelCard.removeAll();
       panelCard.add(new cardApprovals());
       panelCard.repaint();
       panelCard.revalidate();
    }//GEN-LAST:event_btnLogOut3ActionPerformed

    private void btnLogOut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut4ActionPerformed
        // TODO add your handling code here:
         panelCard.removeAll();
       panelCard.add(new cardUsers());
       panelCard.repaint();
       panelCard.revalidate();
    }//GEN-LAST:event_btnLogOut4ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut1;
    private javax.swing.JButton btnLogOut3;
    private javax.swing.JButton btnLogOut4;
    private javax.swing.JButton btnViewGrievance;
    private pgmsapp.cardGrievances cardGrievances1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel panelAdminShow;
    private javax.swing.JPanel panelCard;
    private javax.swing.JTextField tfUName;
    // End of variables declaration//GEN-END:variables
}
