/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pgmsapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author urn
 */
public class cardApprovals extends javax.swing.JPanel {

    /**
     * Creates new form cardGrievances
     */
    int x = 0;
    private boolean up;
    private int ut;
    private Connection con;
    private PreparedStatement ps;
    private ResultSet rsGrievance;
    private String dbName = "";
    private String uName;
    private String email;
    private String uCity;
    private String uAddress;
    private long mobile;
    private int uType;
    private String password;
    private String gCategory;
    private String uDomain;

    public cardApprovals() {
        initComponents();
        panelGShow.setVisible(true);
        panelGView.setVisible(false);
        try {
            up = false;
            ut = 0;
            btnModify.setEnabled(false);
            // TODO add your handling code here:
            //  panelMain.setVisible(false);
            // panelGStatus.setVisible(true);
            con = DriverManager.getConnection("jdbc:mysql://localhost/ugms", "root", "");
            ps = con.prepareStatement("select * from db_approval");
            // ps.setString(1, email);
            rsGrievance = ps.executeQuery();
            if (!rsGrievance.next()) {
                JOptionPane.showMessageDialog(this, "No records found");
            }
            rsGrievance.previous();
            tableUGrievance.setModel(buildTableModel(rsGrievance));
            // tableUGrievance=new JTable(buildTableModel(rsGrievance));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }        // T TODO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelGShow = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUGrievance = new javax.swing.JTable();
        btnModify = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbUType = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        panelGView = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfAddress = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfMobile = new javax.swing.JTextField();
        tfCity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        btnGoBack1 = new javax.swing.JButton();
        btnGoBack2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableUGrievance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableUGrievance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableUGrievance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableUGrievance.setToolTipText("");
        tableUGrievance.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableUGrievance.setAutoscrolls(false);
        tableUGrievance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableUGrievance.setGridColor(new java.awt.Color(0, 0, 0));
        tableUGrievance.setRowMargin(5);
        tableUGrievance.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableUGrievance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUGrievanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUGrievance);

        btnModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnModify.setText("View in Details");
        btnModify.setToolTipText("");
        btnModify.setBorder(null);
        btnModify.setBorderPainted(false);
        btnModify.setContentAreaFilled(false);
        btnModify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModify.setInheritsPopupMenu(true);
        btnModify.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnModify.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("View Reqeusts for");

        cbUType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbUType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "NGO Authority", "Govt Authority", "Admin" }));
        cbUType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUTypeActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("User List");

        javax.swing.GroupLayout panelGShowLayout = new javax.swing.GroupLayout(panelGShow);
        panelGShow.setLayout(panelGShowLayout);
        panelGShowLayout.setHorizontalGroup(
            panelGShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGShowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGShowLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cbUType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGShowLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelGShowLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelGShowLayout.setVerticalGroup(
            panelGShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGShowLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(panelGShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(panelGShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 420));

        panelGView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("User Details-");
        panelGView.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 27));

        tfName.setEditable(false);
        tfName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGView.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 330, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Email");
        panelGView.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 27));

        tfEmail.setEditable(false);
        tfEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGView.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 330, 30));

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfAddress.setEditable(false);
        tfAddress.setBackground(new java.awt.Color(240, 240, 240));
        tfAddress.setColumns(20);
        tfAddress.setLineWrap(true);
        tfAddress.setRows(4);
        jScrollPane3.setViewportView(tfAddress);

        panelGView.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 330, 50));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Address");
        panelGView.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 72, 27));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Mobile");
        panelGView.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, 27));

        tfMobile.setEditable(false);
        tfMobile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGView.add(tfMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 330, -1));

        tfCity.setEditable(false);
        tfCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGView.add(tfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 330, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("City");
        panelGView.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 40, 27));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("User Name");
        panelGView.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 27));

        btnGoBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/reject-normal.png"))); // NOI18N
        btnGoBack.setToolTipText("");
        btnGoBack.setBorder(null);
        btnGoBack.setBorderPainted(false);
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBack.setInheritsPopupMenu(true);
        btnGoBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/reject-clicked.png"))); // NOI18N
        btnGoBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/reject-nouseover.png"))); // NOI18N
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        panelGView.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 120, 50));

        btnGoBack1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGoBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnGoBack1.setText("Go Back");
        btnGoBack1.setToolTipText("");
        btnGoBack1.setBorder(null);
        btnGoBack1.setBorderPainted(false);
        btnGoBack1.setContentAreaFilled(false);
        btnGoBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBack1.setInheritsPopupMenu(true);
        btnGoBack1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnGoBack1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnGoBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack1ActionPerformed(evt);
            }
        });
        panelGView.add(btnGoBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 220, 90));

        btnGoBack2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGoBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/accept-normal.png"))); // NOI18N
        btnGoBack2.setToolTipText("");
        btnGoBack2.setBorder(null);
        btnGoBack2.setBorderPainted(false);
        btnGoBack2.setContentAreaFilled(false);
        btnGoBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBack2.setInheritsPopupMenu(true);
        btnGoBack2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/accept-clicked.png"))); // NOI18N
        btnGoBack2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/accept-mouseover.png"))); // NOI18N
        btnGoBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack2ActionPerformed(evt);
            }
        });
        panelGView.add(btnGoBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 50));

        add(panelGView, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 530, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void tableUGrievanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUGrievanceMouseClicked
        // TODO add your handling code here:
        x = tableUGrievance.getSelectedRow();
        if (x > -1) {
            btnModify.setEnabled(true);
        }
    }//GEN-LAST:event_tableUGrievanceMouseClicked

    public DefaultTableModel buildTableModel(ResultSet rs)
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        
         email = (String) tableUGrievance.getValueAt(x,0);
        uName = (String) tableUGrievance.getValueAt(x, 1);
         uCity = (String) tableUGrievance.getValueAt(x, 3);
        uAddress = (String) tableUGrievance.getValueAt(x, 4);
        mobile = (long) tableUGrievance.getValueAt(x, 5);
        uType=(int) tableUGrievance.getValueAt(x, 2);
        password=(String) tableUGrievance.getValueAt(x, 6);
        gCategory = (String) tableUGrievance.getValueAt(x, 6);
        uDomain=(String) tableUGrievance.getValueAt(x, 8);
        //String gDescription = (String) tableUGrievance.getValueAt(x, 7);
        // gId=(long) tableUGrievance.getValueAt(x, 0);

        tfName.setText(uName);
        tfAddress.setText(uAddress);

        tfCity.setText(uCity);
        tfEmail.setText(email);
        //tfDescription.setText(gDescription);
        tfMobile.setText(mobile+"");
        panelGShow.setVisible(false);
        panelGView.setVisible(true);
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        try {
            // TODO add your handling code here:
            int r=JOptionPane.showConfirmDialog(this, "Sure to Reject?","Alert",JOptionPane.YES_NO_OPTION);
            switch(r)
            {
                case 0:
            ps=con.prepareStatement("delete from db_approval where u_email=?");
            ps.setString(1, email);
            r = ps.executeUpdate();
            if(r>0)
            {
                JOptionPane.showMessageDialog(this, "Rejected");
            }
            }
            // panelGView.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(cardApprovals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void cbUTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUTypeActionPerformed
        // TODO add your handling code here:
        switch (cbUType.getSelectedIndex()) {

            case 0:
            dbName = "";
            break;
            case 1:
            dbName = " where u_type=1";
            break;
            case 2:
            dbName = " where u_type=2";
            break;
            case 3:
            dbName = " where u_type=3";
            break;

        }
        try {
            up = false;
            ut = 0;
            btnModify.setEnabled(false);
            // TODO add your handling code here:
            //  panelMain.setVisible(false);
            // panelGStatus.setVisible(true);
            con = DriverManager.getConnection("jdbc:mysql://localhost/ugms", "root", "");
            ps = con.prepareStatement("select * from db_approval" + dbName);
            // ps.setString(1, email);
            rsGrievance = ps.executeQuery();
            if (!rsGrievance.next()) {
                JOptionPane.showMessageDialog(this, "No records found");
            }
            rsGrievance.previous();
            tableUGrievance.setModel(buildTableModel(rsGrievance));
            // tableUGrievance=new JTable(buildTableModel(rsGrievance));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }        // TODO
    }//GEN-LAST:event_cbUTypeActionPerformed

    private void btnGoBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack1ActionPerformed
        // TODO add your handling code here:
          panelGView.setVisible(false);
        panelGShow.setVisible(true);
    }//GEN-LAST:event_btnGoBack1ActionPerformed

    private void btnGoBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack2ActionPerformed
        try {
            // TODO add your handling code here:
            switch(uType)
            {
                case 0:
                    dbName = "db_user";
                    break;
                case 1:
                    dbName = "db_ngo";
                    break;
                case 2:
                    dbName = "db_govt";
                    
                    break;
                case 3:
                    dbName = "db_admin";
                    break;
                
            }
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/ugms", "root", "");
            
            
            ps = con.prepareStatement("insert into "+dbName+" values(?,?,?,?,?,?,?,?)");
            ps.setString(1, email);
            ps.setString(2, uName);
            ps.setString(3, String.valueOf(uType));
            ps.setString(4, uCity);
            ps.setString(5, uAddress);
            ps.setLong(6, mobile);
            ps.setString(7, password);
            ps.setString(8, uDomain);
            
           int r= ps.executeUpdate();
           if(r>0)
           {
            //JOptionPane.showMessageDialog(this, "Apporved Successfully");
            ps=con.prepareStatement("delete from db_approval where u_email=?");
            ps.setString(1, email);
            r=ps.executeUpdate();
            if(r>0)
           {
            JOptionPane.showMessageDialog(this, "Apporved Successfully");
           }
           }
        } catch (SQLException ex) {
            Logger.getLogger(cardApprovals.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGoBack2ActionPerformed
    public static void main(String args[]) {
        new cardApprovals().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnGoBack1;
    private javax.swing.JButton btnGoBack2;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox<String> cbUType;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelGShow;
    private javax.swing.JPanel panelGView;
    private javax.swing.JTable tableUGrievance;
    private javax.swing.JTextArea tfAddress;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfMobile;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
