/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pgmsapp;

import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author urn
 */
public class cardFundRaiser extends javax.swing.JPanel {

    /**
     * Creates new form cardFundRaiser
     */
    ResultSet rsd;
    int x;
    private Connection con;
    private PreparedStatement ps;
    private float totalAmt;
    private long gId;
    private ResultSet rsGrievance;
    private String uName;
    private String uEmail;
    private long mobile;
    private JPanel panelMainScreen;
    public cardFundRaiser(ResultSet rsd,JPanel panelMainScreen) {
        initComponents();
        try {
            this.rsd=rsd;
            this.panelMainScreen=panelMainScreen;
            panelPayAmount.setVisible(false);
            btnContribute.setEnabled(false);
            con = DriverManager.getConnection("jdbc:mysql://localhost/ugms", "root", "");
            ps = con.prepareStatement("select * from db_fundraiser");
            // ps.setString(1, email);
            rsGrievance = ps.executeQuery();
            if (!rsGrievance.next()) {
                JOptionPane.showMessageDialog(this, "No records found");
            }
            rsGrievance.previous();
            tableFunds.setModel(buildTableModel(rsGrievance));
        } catch (SQLException ex) {
            Logger.getLogger(cardFundRaiser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundraisers = new javax.swing.JPanel();
        btnGoBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFunds = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        btnContribute = new javax.swing.JButton();
        panelPayAmount = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        buttonAddMoney = new javax.swing.JButton();
        btnCancelMoney = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tfCardNo = new javax.swing.JTextField();
        tfMobile = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfCVV = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfGId = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFundraisers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGoBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnGoBack.setText("Go Back");
        btnGoBack.setToolTipText("");
        btnGoBack.setBorder(null);
        btnGoBack.setBorderPainted(false);
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBack.setInheritsPopupMenu(true);
        btnGoBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnGoBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        panelFundraisers.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 230, 70));

        tableFunds.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableFunds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableFunds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableFunds.setToolTipText("");
        tableFunds.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableFunds.setAutoscrolls(false);
        tableFunds.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableFunds.setGridColor(new java.awt.Color(0, 0, 0));
        tableFunds.setRowMargin(5);
        tableFunds.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableFunds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFundsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFunds);

        panelFundraisers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 530, 202));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Active Fundraisers");
        panelFundraisers.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btnContribute.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnContribute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnContribute.setText("Contribute");
        btnContribute.setToolTipText("");
        btnContribute.setBorder(null);
        btnContribute.setBorderPainted(false);
        btnContribute.setContentAreaFilled(false);
        btnContribute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContribute.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContribute.setInheritsPopupMenu(true);
        btnContribute.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnContribute.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnContribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContributeActionPerformed(evt);
            }
        });
        panelFundraisers.add(btnContribute, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 220, 70));

        add(panelFundraisers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 620, 390));

        panelPayAmount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfName.setEditable(false);
        tfName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelPayAmount.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 300, 30));

        tfEmail.setEditable(false);
        tfEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelPayAmount.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 300, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Name");
        panelPayAmount.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 70, 27));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Email");
        panelPayAmount.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 27));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("G-ID");
        panelPayAmount.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 60, 30));

        buttonAddMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonAddMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/accept-normal.png"))); // NOI18N
        buttonAddMoney.setToolTipText("");
        buttonAddMoney.setBorder(null);
        buttonAddMoney.setBorderPainted(false);
        buttonAddMoney.setContentAreaFilled(false);
        buttonAddMoney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAddMoney.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAddMoney.setInheritsPopupMenu(true);
        buttonAddMoney.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/accept-clicked.png"))); // NOI18N
        buttonAddMoney.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/accept-mouseover.png"))); // NOI18N
        buttonAddMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddMoneyActionPerformed(evt);
            }
        });
        panelPayAmount.add(buttonAddMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 50));

        btnCancelMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/reject-normal.png"))); // NOI18N
        btnCancelMoney.setToolTipText("");
        btnCancelMoney.setBorder(null);
        btnCancelMoney.setBorderPainted(false);
        btnCancelMoney.setContentAreaFilled(false);
        btnCancelMoney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelMoney.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelMoney.setInheritsPopupMenu(true);
        btnCancelMoney.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/reject-clicked.png"))); // NOI18N
        btnCancelMoney.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/reject-nouseover.png"))); // NOI18N
        btnCancelMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelMoneyActionPerformed(evt);
            }
        });
        panelPayAmount.add(btnCancelMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 120, 50));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Card No");
        panelPayAmount.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 70, 30));

        tfCardNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelPayAmount.add(tfCardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 300, 30));

        tfMobile.setEditable(false);
        tfMobile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelPayAmount.add(tfMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 300, 30));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("CVV");
        panelPayAmount.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 60, 30));

        tfCVV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelPayAmount.add(tfCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 100, 30));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", " " }));
        panelPayAmount.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 60, 30));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", " " }));
        panelPayAmount.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 60, 30));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Expiry ");
        panelPayAmount.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 80, 30));

        tfAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelPayAmount.add(tfAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 110, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Amount($)");
        panelPayAmount.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 80, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Mobile");
        panelPayAmount.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 60, 30));

        tfGId.setEditable(false);
        tfGId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelPayAmount.add(tfGId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, 30));

        add(panelPayAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 630, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void tableFundsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFundsMouseClicked
        // TODO add your handling code here:
        x = tableFunds.getSelectedRow();
        if (x > -1) {
            btnContribute.setEnabled(true);
        }
        
    }//GEN-LAST:event_tableFundsMouseClicked

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
      //  panelGView.setVisible(false);
        //panelGShow.setVisible(true);
        // panelGView.setEnabled(false);
        this.removeAll();
        this.add(panelMainScreen);
        this.repaint();
        this.revalidate();
        
        
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnCancelMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelMoneyActionPerformed
       // TODO add your handling code here:
           
    }//GEN-LAST:event_btnCancelMoneyActionPerformed

     public DefaultTableModel buildTableModel(ResultSet rs)
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }
    
    private void buttonAddMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddMoneyActionPerformed
       

        try {
           // gId=(long) tableFunds.getValueAt(x, 0);
        //totalAmt=(Float) tableFunds.getValueAt(x, 2);
            con = DriverManager.getConnection("jdbc:mysql://localhost/ugms", "root", "");

            ps = con.prepareStatement("update db_fundraiser set total_fund=? where g_id=?");
            totalAmt+=Float.parseFloat(tfAmount.getText());
            ps.setFloat(1, totalAmt);
            ps.setLong(2, gId);

            int r= ps.executeUpdate();
            if(r>0)
            {
                //JOptionPane.showMessageDialog(this, "Apporved Successfully");
               
                    JOptionPane.showMessageDialog(this, "Payment Successful");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(cardFundRaiser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonAddMoneyActionPerformed

    private void btnContributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContributeActionPerformed
        try {
            // TODO add your handling code here
            gId=(long) tableFunds.getValueAt(x, 0);
            uName=rsd.getString("u_name");
            uEmail=rsd.getString("u_email");
            mobile=rsd.getLong("u_mobile");
            tfEmail.setText(uEmail);
            tfGId.setText(gId+"");
            tfMobile.setText(mobile+"");
            tfName.setText(uName);
            
            totalAmt=(Float) tableFunds.getValueAt(x, 2);
            panelPayAmount.setVisible(true);
            panelFundraisers.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(cardFundRaiser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnContributeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelMoney;
    private javax.swing.JButton btnContribute;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton buttonAddMoney;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFundraisers;
    private javax.swing.JPanel panelPayAmount;
    private javax.swing.JTable tableFunds;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextField tfCVV;
    private javax.swing.JTextField tfCardNo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfGId;
    private javax.swing.JTextField tfMobile;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
