/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pgmsapp;

import static java.awt.SystemColor.window;
import java.awt.Window;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author urn
 */
public class GrievanceRegister extends javax.swing.JFrame {

    /**
     * Creates new form GrievanceRegister
     */
    String email, uname, gCity, gCategory, gSubCategory, gAddress, gLandMark, gDescription;
    ResultSet rs;
    Connection con;
    PreparedStatement ps;
    private int ut;
    private String dbName;
    private String s;

    public GrievanceRegister(ResultSet rs) {
        this.rs = rs;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        panelGInfo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfCity = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescription = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfAddress = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        tfLandmark = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfImage = new javax.swing.JTextField();
        btnChooseImage = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        btnRegGrievance = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grievance Registration");
        setLocation(new java.awt.Point(200, 200));
        setMaximumSize(new java.awt.Dimension(800, 520));
        setMinimumSize(new java.awt.Dimension(800, 520));
        setPreferredSize(new java.awt.Dimension(800, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Griveance Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 0, 51))); // NOI18N
        panelGInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Description (Max 400 Words)");
        panelGInfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 95, 229, 27));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("City");
        panelGInfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 45, 27));

        tfName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGInfo.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 53, 312, -1));

        tfCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGInfo.add(tfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 53, 190, -1));

        cbCategory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Infrastructure Related Grievance", "Health Related Grievance", "Personal Grievances", "Financial Grievances", "Environment Related Grievance" }));
        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });
        panelGInfo.add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 128, 312, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Select a Grievence Category : ");
        panelGInfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 95, -1, 27));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Name");
        panelGInfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 50, 72, 27));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfDescription.setColumns(20);
        tfDescription.setLineWrap(true);
        tfDescription.setRows(4);
        jScrollPane1.setViewportView(tfDescription);

        panelGInfo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 128, 248, 237));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Address");
        panelGInfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 179, 72, 27));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfAddress.setColumns(20);
        tfAddress.setLineWrap(true);
        tfAddress.setRows(4);
        jScrollPane2.setViewportView(tfAddress);

        panelGInfo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 179, 312, 60));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Landmark");
        panelGInfo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 257, 80, 27));

        tfLandmark.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGInfo.add(tfLandmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 260, 310, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Upload an Image (Size 100kb-400kb)");
        panelGInfo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 302, 296, 27));

        tfImage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGInfo.add(tfImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 341, 271, -1));

        btnChooseImage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnChooseImage.setText("Choose Image");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });
        panelGInfo.add(btnChooseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 340, -1, -1));

        getContentPane().add(panelGInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 390));

        btnGoBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnGoBack.setText("Go Back");
        btnGoBack.setToolTipText("");
        btnGoBack.setBorder(null);
        btnGoBack.setBorderPainted(false);
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBack.setInheritsPopupMenu(true);
        btnGoBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnGoBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 218, 70));

        btnRegGrievance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegGrievance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnRegGrievance.setText("Register Grievance");
        btnRegGrievance.setToolTipText("");
        btnRegGrievance.setBorder(null);
        btnRegGrievance.setBorderPainted(false);
        btnRegGrievance.setContentAreaFilled(false);
        btnRegGrievance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegGrievance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegGrievance.setInheritsPopupMenu(true);
        btnRegGrievance.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnRegGrievance.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnRegGrievance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegGrievanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegGrievance, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 212, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void btnRegGrievanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegGrievanceActionPerformed
        try {
            ut = rs.getInt("u_type");

            switch (ut) {
                case 0:
                    dbName = "db_grievance";

                    break;
                case 1:
                    dbName = "db_ngo_grievance";

                    break;

            }
            email = rs.getString("u_email");
            uname = tfName.getText();
            gCity = tfCity.getText();
            gCategory = cbCategory.getSelectedItem().toString();
           // gSubCategory = cbSubCategory.getSelectedItem().toString();
            gAddress = tfAddress.getText();
            gLandMark = tfLandmark.getText();
            gDescription = tfDescription.getText();
            if (uname.isEmpty() || gCity.isEmpty() || gAddress.isEmpty() || gLandMark.isEmpty() || gDescription.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please fill all the Details");
            } else {
                con = DriverManager.getConnection("jdbc:mysql://localhost/ugms", "root", "");
                InputStream is = new FileInputStream(new File(s));
                

                ps = con.prepareStatement("INSERT INTO `" + dbName + "`(`u_email`,`u_name`, `g_city`, `g_address`, `g_landmark`, `g_category`, `g_description`, `g_image`, `g_status`) VALUES(?,?,?,?,?,?,?,?,?)");
                ps.setString(1, email);
                ps.setString(2, uname);
                ps.setString(3, gCity);
                ps.setString(4, gAddress);
                ps.setString(5, gLandMark);
                ps.setString(6, gCategory);
                ps.setString(7, gDescription);
                ps.setBlob(8, is);
                ps.setString(9, "Pending");
                int r = ps.executeUpdate();
                if (r > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Grievance has been Submitted");
                }

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GrievanceRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegGrievanceActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        try {
           ut= rs.getInt("u_type");
            // TODO add your handling code here:
            if(ut==0)
            {
            this.dispose();
            new GrievanceMenu(rs).setVisible(true);
            }
            else
            {
                 this.dispose();
            new NgoPortal(rs).setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrievanceRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed

        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            //lbl.setIcon(ResizeImage(path));
            s = path;
            tfImage.setText(s);

        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null,"No Data");
        }

    

    }//GEN-LAST:event_btnChooseImageActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrievanceRegister.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrievanceRegister.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrievanceRegister.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrievanceRegister.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new GrievanceRegister(rs).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnRegGrievance;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelGInfo;
    private javax.swing.JTextArea tfAddress;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextArea tfDescription;
    private javax.swing.JTextField tfImage;
    private javax.swing.JTextField tfLandmark;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
