/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pgmsapp;

import java.awt.Image;
import java.sql.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author urn
 */
public class GrievanceMenu extends javax.swing.JFrame {

    /**
     * Creates new form GrievanceMenu
     */
    ResultSet rs,rsGrievance;
    PreparedStatement ps,ps2;
    Connection con;
    String email;
    int x=-1;
    int ut=0;
    //private Object rsImage;
    ResultSet rsImage;
    private Image im;
    private long gId;
    private Float totalAmount;
    public GrievanceMenu(ResultSet rs) throws SQLException {
        initComponents();
         btnModify.setEnabled(false);
        //panelMain.setVisible();
        this.rs=rs;
        ut=rs.getInt("u_type");
        email=rs.getString("u_email");
        panelGStatus.setVisible(false);
        lblHello.setText("Hello "+rs.getString("u_name")+", how can we help you? (Choose an option)" );
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ugmsPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ugmsPU").createEntityManager();
        dbGrievanceQuery = java.beans.Beans.isDesignTime() ? null : ugmsPUEntityManager.createQuery("SELECT d FROM DbGrievance d");
        dbGrievanceList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dbGrievanceQuery.getResultList();
        dbGrievanceQuery1 = java.beans.Beans.isDesignTime() ? null : ugmsPUEntityManager.createQuery("SELECT d FROM DbGrievance d");
        dbGrievanceList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dbGrievanceQuery1.getResultList();
        dbGrievanceQuery2 = java.beans.Beans.isDesignTime() ? null : ugmsPUEntityManager.createQuery("SELECT d FROM DbGrievance d");
        dbGrievanceList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dbGrievanceQuery2.getResultList();
        dbGrievanceQuery3 = java.beans.Beans.isDesignTime() ? null : ugmsPUEntityManager.createQuery("SELECT d FROM DbGrievance d");
        dbGrievanceList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dbGrievanceQuery3.getResultList();
        panelMain = new javax.swing.JPanel();
        panelMainScreen = new javax.swing.JPanel();
        btnGStatus = new javax.swing.JButton();
        btnDonateMenu = new javax.swing.JButton();
        btnGRegister = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblHello = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelGStatus = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUGrievance = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Portal");
        setLocation(new java.awt.Point(200, 200));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelMainScreen.setMaximumSize(new java.awt.Dimension(560, 330));
        panelMainScreen.setMinimumSize(new java.awt.Dimension(571, 330));
        panelMainScreen.setPreferredSize(new java.awt.Dimension(560, 330));
        panelMainScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnGStatus.setText("View Grievance Status");
        btnGStatus.setToolTipText("");
        btnGStatus.setBorder(null);
        btnGStatus.setBorderPainted(false);
        btnGStatus.setContentAreaFilled(false);
        btnGStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGStatus.setInheritsPopupMenu(true);
        btnGStatus.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnGStatus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnGStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGStatusActionPerformed(evt);
            }
        });
        panelMainScreen.add(btnGStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, 45));

        btnDonateMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDonateMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnDonateMenu.setText("Donate for a Cause");
        btnDonateMenu.setToolTipText("");
        btnDonateMenu.setBorder(null);
        btnDonateMenu.setBorderPainted(false);
        btnDonateMenu.setContentAreaFilled(false);
        btnDonateMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonateMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonateMenu.setInheritsPopupMenu(true);
        btnDonateMenu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnDonateMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnDonateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateMenuActionPerformed(evt);
            }
        });
        panelMainScreen.add(btnDonateMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        btnGRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnGRegister.setText("Register new Grievance");
        btnGRegister.setToolTipText("");
        btnGRegister.setBorder(null);
        btnGRegister.setBorderPainted(false);
        btnGRegister.setContentAreaFilled(false);
        btnGRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGRegister.setInheritsPopupMenu(true);
        btnGRegister.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnGRegister.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnGRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGRegisterActionPerformed(evt);
            }
        });
        panelMainScreen.add(btnGRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 47));

        btnLogOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.setToolTipText("");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut.setInheritsPopupMenu(true);
        btnLogOut.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnLogOut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        panelMainScreen.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/user_menu.png"))); // NOI18N
        panelMainScreen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 111, 150, 210));

        lblHello.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHello.setText("Hello xxx, how can we help you? (Choose an option) ");
        panelMainScreen.add(lblHello, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Personal Info");
        panelMainScreen.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Request for changes in");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panelMainScreen.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        panelMain.add(panelMainScreen, "card11");

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 720, 450));

        panelGStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Select any Grievance to View/Modify", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N
        panelGStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableUGrievance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableUGrievance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableUGrievance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableUGrievance.setToolTipText("");
        tableUGrievance.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableUGrievance.setAutoscrolls(false);
        tableUGrievance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableUGrievance.setGridColor(new java.awt.Color(0, 0, 0));
        tableUGrievance.setRowMargin(5);
        tableUGrievance.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableUGrievance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUGrievanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUGrievance);
        tableUGrievance.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        panelGStatus.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 44, 630, 260));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnBack.setText("Go Back");
        btnBack.setToolTipText("");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.setInheritsPopupMenu(true);
        btnBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panelGStatus.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 230, 80));

        btnModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnModify.setText("View/Modify");
        btnModify.setToolTipText("");
        btnModify.setBorder(null);
        btnModify.setBorderPainted(false);
        btnModify.setContentAreaFilled(false);
        btnModify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModify.setInheritsPopupMenu(true);
        btnModify.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnModify.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        panelGStatus.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 230, 80));

        getContentPane().add(panelGStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 680, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGRegisterActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new GrievanceRegister(rs).setVisible(true);
    }//GEN-LAST:event_btnGRegisterActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        try {
            // TODO add your handling code here:
            new PGMSLogin().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(GrievanceMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            // TODO add your handling code here:
            //panelSignup.setVisible(true);
            //panelLogin.setVisible(false);
            con=DriverManager.getConnection("jdbc:mysql://localhost/ugms","root","");
            PreparedStatement psAdmin=con.prepareStatement("select u_name,u_email from db_admin");
            ResultSet rsAdmin=psAdmin.executeQuery();
            String strMsg="Admin Names     Emails";
            while(rsAdmin.next())
            {
                strMsg+="\n"+rsAdmin.getString(1)+" - "+rsAdmin.getString(2);
                
            }
            JOptionPane.showMessageDialog(this, strMsg, "Please contact any of the admins", 1);
        } catch (SQLException ex) {
            Logger.getLogger(GrievanceMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnDonateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateMenuActionPerformed
        // TODO add your handling code here:
     //panelMain.removeAll();
     this.dispose();
       new FundRaisers(rs).setVisible(true);
      // panelMain.repaint();
       //panelMain.revalidate();
    }//GEN-LAST:event_btnDonateMenuActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        panelMain.setVisible(true);
        panelGStatus.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        try {
            totalAmount=(Float)tableUGrievance.getValueAt(x, 11);
           
            // TODO add your handling code here:
            String gName=(String) tableUGrievance.getValueAt(x, 2);
            String gCity=(String) tableUGrievance.getValueAt(x, 3);
            String gAddress=(String) tableUGrievance.getValueAt(x, 4);
            String gLandMark=(String) tableUGrievance.getValueAt(x, 5);
            String gCategory=(String) tableUGrievance.getValueAt(x, 6);
            String gDescription=(String) tableUGrievance.getValueAt(x, 7);
            gId=(long) tableUGrievance.getValueAt(x, 0);
             if(totalAmount>0)
            {
                JOptionPane.showMessageDialog(this, "Fundraising Initiated for your Grievance \n Please Open Active Fundraisers Status and Search for id = " +gId);
            }
            ps2=con.prepareStatement("select * from db_grievance where g_id=?");
            ps2.setLong(1, gId);
            rsImage=ps2.executeQuery();
            if(rsImage.next())
            {
                //rsImage.previous();
                Blob filenameBlob = rsImage.getBlob("g_image");
            byte[] img = filenameBlob.getBytes(1L,(int)filenameBlob.length());
            ImageIcon image = new ImageIcon(img);
                    im = image.getImage();
            } 
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Image not found");
            }
            
                    
            
            
            this.dispose();
            new GrievanceUpdate(gId,gName,gCity,gAddress,gCategory, gLandMark,gDescription,im,ut,true,rs).setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(GrievanceMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnGStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGStatusActionPerformed
        try {
            btnModify.setEnabled(false);
            // TODO add your handling code here:
            panelMain.setVisible(false);
            panelGStatus.setVisible(true);
            con=DriverManager.getConnection("jdbc:mysql://localhost/ugms","root","");
            ps=con.prepareStatement("select * from db_grievance where u_email=?");
            ps.setString(1, email);
            rsGrievance=ps.executeQuery();
            if(!rsGrievance.next())
            {
                JOptionPane.showMessageDialog(rootPane, "No records found");
            }
            rsGrievance.previous();
            tableUGrievance.setModel(buildTableModel(rsGrievance));
            // tableUGrievance=new JTable(buildTableModel(rsGrievance));
        
             
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
        
    }//GEN-LAST:event_btnGStatusActionPerformed

    private void tableUGrievanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUGrievanceMouseClicked
        // TODO add your handling code here:
         x=tableUGrievance.getSelectedRow();
        if(x>-1)
        {
            btnModify.setEnabled(true);
        }
    }//GEN-LAST:event_tableUGrievanceMouseClicked

    public DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrievanceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrievanceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrievanceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrievanceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GrievanceMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDonateMenu;
    private javax.swing.JButton btnGRegister;
    private javax.swing.JButton btnGStatus;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnModify;
    private java.util.List<pgmsapp.DbGrievance> dbGrievanceList;
    private java.util.List<pgmsapp.DbGrievance> dbGrievanceList1;
    private java.util.List<pgmsapp.DbGrievance> dbGrievanceList2;
    private java.util.List<pgmsapp.DbGrievance> dbGrievanceList3;
    private javax.persistence.Query dbGrievanceQuery;
    private javax.persistence.Query dbGrievanceQuery1;
    private javax.persistence.Query dbGrievanceQuery2;
    private javax.persistence.Query dbGrievanceQuery3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHello;
    private javax.swing.JPanel panelGStatus;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMainScreen;
    private javax.swing.JTable tableUGrievance;
    private javax.persistence.EntityManager ugmsPUEntityManager;
    // End of variables declaration//GEN-END:variables
}
