/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pgmsapp;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author urn
 */
public class GrievanceUpdate extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement ps;
    private String email;
    private String uname;
    private String gCity;
    private String gAddress;
    private String gLandMark;
    private String gCategory;
    private String gDescription;
    private long gId;
    private String gSubCategory;
    int ut;
    private String dbName;
    private boolean up;
    ResultSet rs;
    /**
     * Creates new form GrievanceRegister
     */
    public GrievanceUpdate(long gId,String uName, String gCity, String gAddress,String gCategory, String gLandMark, String gDescription,Image im,int utype,boolean up,ResultSet rs) {
        initComponents();
        cbCategory.getModel().setSelectedItem(gCategory);
        this.rs=rs;
        this.gId=gId;
        tfName.setText(uName);
        tfAddress.setText(gAddress);
        tfLandMark.setText(gLandMark);
        tfCity.setText(gCity);
        tfDescription.setText(gDescription);
        ut=utype;
        this.up=up;
        Image myImg = im.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lblImage.setIcon(newImage);
        if(!up)
        {
            btnUpdateGrievance.setEnabled(false);
        }
    }

   

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        panelGInfo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfCity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescription = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfAddress = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        tfLandMark = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        btnGoBack = new javax.swing.JButton();
        btnUpdateGrievance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Grievance");
        setLocation(new java.awt.Point(200, 200));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Griveance Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 0, 51))); // NOI18N
        panelGInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Description (Max 400 Words)");
        panelGInfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 50, 229, 27));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("City");
        panelGInfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 45, 27));

        tfName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGInfo.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 312, -1));

        tfCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGInfo.add(tfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 165, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Select a Grievence Category : ");
        panelGInfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 27));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Name");
        panelGInfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 72, 27));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfDescription.setColumns(20);
        tfDescription.setLineWrap(true);
        tfDescription.setRows(4);
        jScrollPane1.setViewportView(tfDescription);

        panelGInfo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 83, 270, 97));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Address");
        panelGInfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 72, 27));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfAddress.setColumns(20);
        tfAddress.setLineWrap(true);
        tfAddress.setRows(4);
        jScrollPane2.setViewportView(tfAddress);

        panelGInfo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 312, 60));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Landmark");
        panelGInfo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 40));

        tfLandMark.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelGInfo.add(tfLandMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 310, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Uploaded Image ");
        panelGInfo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 186, 147, 27));
        panelGInfo.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 230, 140));

        cbCategory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infrastructure Related Grievance", "Health Related Grievance", "Personal Grievances", "Environment Related Grievance", "Financial Grievances", "Other" }));
        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });
        panelGInfo.add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 312, -1));

        getContentPane().add(panelGInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 31, 750, 380));

        btnGoBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnGoBack.setText("Go Back");
        btnGoBack.setToolTipText("");
        btnGoBack.setBorder(null);
        btnGoBack.setBorderPainted(false);
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBack.setInheritsPopupMenu(true);
        btnGoBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnGoBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 218, 67));

        btnUpdateGrievance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateGrievance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_normal.png"))); // NOI18N
        btnUpdateGrievance.setText("Update Grievance");
        btnUpdateGrievance.setToolTipText("");
        btnUpdateGrievance.setBorder(null);
        btnUpdateGrievance.setBorderPainted(false);
        btnUpdateGrievance.setContentAreaFilled(false);
        btnUpdateGrievance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateGrievance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateGrievance.setInheritsPopupMenu(true);
        btnUpdateGrievance.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_clicked.png"))); // NOI18N
        btnUpdateGrievance.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pgmsapp/button_mouseover.png"))); // NOI18N
        btnUpdateGrievance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGrievanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateGrievance, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 212, 67));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateGrievanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGrievanceActionPerformed
        try {
            uname = tfName.getText();
            gCity = tfCity.getText();
            gCategory = cbCategory.getSelectedItem().toString();
           // gSubCategory = cbgSubCategory.getSelectedItem().toString();
            gAddress = tfAddress.getText();
            gLandMark = tfLandMark.getText();
            gDescription = tfDescription.getText();
            if (uname.isEmpty()|| gCity.isEmpty() || gAddress.isEmpty() || gLandMark.isEmpty() || gDescription.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please fill all the Details");
            } else {
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:mysql://localhost/ugms", "root", "");
            switch(ut)
            {
                case 0:
                    dbName="db_grievance";
                    up=true;
                    break;
                case 1:
                    dbName="db_ngo_grievance";
                    up=false;
                    break;
            }
            ps = con.prepareStatement("update "+dbName+" set `u_name`=?, `g_city`=?, `g_address`=?, `g_landmark`=?, `g_category`=?, `g_description`=? where g_id=?");
           // ps.setString(1,email );
            ps.setString(1, uname);
            ps.setString(2, gCity);
            ps.setString(3, gAddress);
            ps.setString(4, gLandMark);
            ps.setString(5, gCategory);
            ps.setString(6, gDescription);
            //ps.setString(7, "NULL");
            ps.setLong(7, gId);
            int r=ps.executeUpdate();
            if(r>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Grievance has been Updated");
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrievanceUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateGrievanceActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
         try {
           ut= rs.getInt("u_type");
            // TODO add your handling code here:
            if(ut==0)
            {
            this.dispose();
            new GrievanceMenu(rs).setVisible(true);
            }
            else
            {
                 this.dispose();
            new NgoPortal(rs).setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrievanceRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrievanceUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrievanceUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrievanceUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrievanceUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GrievanceUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnUpdateGrievance;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel panelGInfo;
    private javax.swing.JTextArea tfAddress;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextArea tfDescription;
    private javax.swing.JTextField tfLandMark;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
